### ISSUE TITLE
Need for clarification on the status of this plugin 

### ISSUE THREAD

**Issue by Greybird** [baritonehands/jenkinsnuget#2]
Hi,

I’m currently working on a plugin to allow publishing packages to nuget servers.
From googling the need, it appeared that the recommended way is to store api key in environement variables, but this does not fit with security needs of my organization as these variables can then be extracted very easily.
The idea is mainly to allow configuration of api keys in the global configuration, and to provide a post build task pushing to nuget using one of the api keys configured at system level.

I then discovered your nuget plugin, which is providing a trigger based on nuget.
I then found that repos on jenkinsci and your repo are not in sync,
Jenkins plugin page references jenkinsci repo, but the releases history seems to ft more with yours.
I also see an open pull request on the jenkinsci fork.

Could you please tell me if:
- you still maintain this plugin?
- there is an issue with the wiki page/the jenkinsci repo?
- you are open to a contribution regarding publication to nuget servers or if I should go with a separate plugin?

Thanks!

Arnaud

**Comment by baritonehands** [comment]
If your organization plans to use this, you can become a contributor or
take ownership. I have changed jobs and am no longer using NuGet.

You're right though, my repo is the most up to date. I opened that pull
request forever ago but they are slow to merge them. Also, you may need the
run-condition plugin which I had to modify to fix a bug which also hasn't
been merged.

For your problem description, if this is an internal nuget repo, you can
just copy the file into the repo directory. That's what we did instead of
publishing via api.

**Comment by Greybird** [comment]
Hi,artie

Thanks for your answer!

Unfortunately, we have nuget servers under our control, but also others using thirdparties (like nexus) , or not under our control. Also, with latest nuget server versions, directory structure is not flat anymore, leading to potential issues when copying .nupkg files. We would also like to have a fine-grained control on publication.

I found your contribution to run-condition, and will take a look at it too.

I will develop the new feature based on your repo.
Once ready, I will recontact you so that we can agree on the best direction to take regarding ownership and contribution.

Thanks,

Arnaud

**Comment by Greybird** [comment]
Hi,

Development of the feature is nearly done:
https://github.com/Greybird/jenkinsnuget/commits/add-nuget-publication
I took the opportunity to do some cleanup.

I still need to test it on Monday on our development instance at work, to check that everything goes fine between master and slaves, as I did not go through the setup process on my dev machine.

If you are ok with this, I will ask for rights to become co owner of the plugin on jenkins dev list ?

Feel free to rase any concerns/remarks!

Arnaud

**Comment by baritonehands** [comment]
I think I can just go in and give you rights. It's been awhile, I can't remember exactly how the release process goes. I will look into what I need to do.

Brian

**Comment by Greybird** [comment]
Thanks!

**Comment by Greybird** [comment]
Hi,

Hope you are having a good day!
Did you manage to find what to do ?

If not, it seems everything has to go from the jenkins dev mailing list, to add jira/jenkinsci repo/release access.
I can do the needed by myself if it saves you time ?

Arnaud

**Comment by baritonehands** [comment]
I was able to release from my local machine, it doesn't have to go through
the jenkinsci repo. But you might as well try to do that.

I will take a look this afternoon. I can't remember what credentials I
needed to publish.

**Comment by baritonehands** [comment]
I would always follow the instructions here to release: https://wiki.jenkins-ci.org/display/JENKINS/Hosting+Plugins. You just need to create an account at jenkins-ci.org and publish I think. Try and it see if you get a permission error or anything.

**Comment by Greybird** [comment]
Hi,
As the document states that releases must happen from jenkinsci repo, I created the following tickets to get access:
- https://issues.jenkins-ci.org/browse/HOSTING-66
- https://issues.jenkins-ci.org/browse/HOSTING-70

I think things are in good shape and will be settled soon!

Arnaud

**Comment by Greybird** [comment]
Hi,

Version 0.5 released.
I have been able to merge your pull requests as I got every right needed.

Last recommendation could be to remove your repository to make jenkinsci appear to be the main one.
But this is not a big deal.

Thanks a lot for your help and time in this process!

Arnaud

**Comment by baritonehands** [comment]
Thanks for taking over maintenance. I'm happy it was useful for you.
